### ISSUE TITLE
Quick tour documentation does not provide a good experience to a windows user 

### ISSUE THREAD

**Issue by DhanushkiMapitigama** [ballerina-platform/ballerina-www#1010]
Had to find commands myself to complete the quick tour. (For example curl commands quotation marks)
It's better if you can include them. And the 'composer' command conflicts with PHP Dependency Management composer.  So it's better if you can mention it. (Better if you try to change the command since PHP Dependency Management composer is somewhat popular.)

ballerina version: 0.975.1

**Comment by namila007** [comment]
I had the same issue, i also have the php composer, so this wont run, need to goto the file path and run the bat file.

**Comment by anupama-pathirage** [comment]
Related issue https://github.com/ballerina-platform/ballerina-lang/issues/9442 and https://github.com/ballerina-platform/ballerina-lang/issues/9659

**Comment by ayomawdb** [comment]
Since https://github.com/ballerina-platform/ballerina-lang/issues/9442 is used to track the name conflict, there is one other concern related to "Quick Tour" left to be addressed in this issue. 

I have verified the commands and the flow followed in the latest "Quick Tour" page, with Linux and Windows. This is based on Ballerina 0.981.1. There seems to be no problem as of now. I believe @DhanushkiMapitigama  was referring to the page not using quotation marks to wrap URLs when writing cURL commands. Not having quotation marks was not a problem in both Linux and Windows with the command we have listed now (we are not passing any arguments to the samples in quick tour that might require "&" with which quotations are required). 

If you are experience an issue in a different environment or still experience same issue, please reopen with further details.
