### ISSUE TITLE
Quick tour Hello world code throws error when run

### ISSUE THREAD

**Issue by Aaquiff** [ballerina-platform/ballerina-www#1341]
**Description:**
While trying to run the client code given in the quick guide, the following error is thrown. Plugin for VSCode indicates that the error is at line 12 where the else statement is followed with a predicate. Altering this to an else if condition seems to work fine.

```
error: .::main.bal:12:12: invalid token '('
error: .::main.bal:15:1: extraneous input '}'
```

Affected Product Version:
Ballerina 0.990.2

OS, DB, other environment details and versions:
Mac OS 10.13.6

**Steps to reproduce:**
Create file main.bal with the given code and run
```
import ballerina/http;
import ballerina/log;
import ballerina/io;

http:Client clientEndpoint = new("http://localhost:9090");

public function main() {
    // Send a GET request to the Hello World service endpoint.
    var response = clientEndpoint->get("/hello/sayHello");
    if (response is http:Response) {
        io:println(response.getTextPayload());
    } else (response is error) {
        log:printError("Get request failed", err = response);
    }
}
```

**Comment by MaryamZi** [comment]
Yes, the following line of code is incorrect.
```ballerina
else (response is error) {
```

We can even say `else` here (instead of an `else if`) since with the type guard, the type is inferred in the `else` block where possible. 
```ballerina
else {
```

Since the type of `response` (the return type of `clientEndpoint->get("/hello/sayHello")`) is  `http:Response|error`, and the `http:Response` scenario is handled in the `if` block, the type would be `error` in the `else` block.

**Updated Sample:**
```ballerina
import ballerina/http;
import ballerina/log;
import ballerina/io;

http:Client clientEndpoint = new("http://localhost:9090");

public function main() {
    // Send a GET request to the Hello World service endpoint.
    var response = clientEndpoint->get("/hello/sayHello");
    if (response is http:Response) {
        io:println(response.getTextPayload());
    } else {
        log:printError("Get request failed", err = response);
    }
}
```

This sample needs to be updated.

**Comment by riyafa** [comment]
Fixed in https://github.com/ballerina-platform/ballerina-www/pull/1343
