### ISSUE TITLE
Unable to find suppressions file at location error[Installing from git source via mvn]

### ISSUE THREAD

**Issue by AnjanaSenanayake** [ballerina-platform/ballerina-www#972]
**Description:**
while insatlling ballerina from git source using mvn clean install follwing error ocurred:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (validate) on project ballerina-parent: Failed during checkstyle execution: Unable to find suppressions file at location: https://raw.githubusercontent.com/wso2/code-quality-tools/v1.1/checkstyle/suppressions.xml: Could not find resource 'https://raw.githubusercontent.com/wso2/code-quality-tools/v1.1/checkstyle/suppressions.xml'. -> [Help 1]

**OS, DB, other environment details and versions:**    

On Ubuntu 18.04 x86_64, #21-Ubuntu SMP

**Steps to reproduce:**

1) clone source from git.
2) run 'mvn clean install' from the repository root directory.

**Comment by anupama-pathirage** [comment]
@AnjanaSenanayake This is occurred due to a network issue in your end. Please check the connectivity and whether you can access the file in the location [1] This file contains the check style suppression details and it is hosted in github repo.

[1]  https://raw.githubusercontent.com/wso2/code-quality-tools/v1.1/checkstyle/suppressions.xml

If you have further queries please feel free to contact us.
